#!/bin/bash
echo "== list objects"

if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket --bucket $BUCKET_NAME --profile AdministratorAccess-952346071138 \
--query Location \
--output text