AWSTemplateFormatVersion: '2010-09-09'
Description: S3 CloudFormation
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: example-bucket-aws-carter-4567